'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Clock3, MapPin, Minus, Plus, ShoppingCart, Star, Truck, X } from 'lucide-react';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient('https://zjeclsozvjymuzwyhvqj.supabase.co','sb_publishable_WyjaTHvDUwGPCwHaXcdApw_xlssm0TE');
const LOGO='https://hey-roll-lets-go.vercel.app/images/hey-roll-logo.png';
const WA='5585992443472';
type Product={product_id:string;category_name:string|null;product_name:string;product_description:string|null;product_price:number;product_image_url:string|null;product_badge:string|null};
type CartItem=Product&{quantity:number};
type Checkout={name:string;phone:string;street:string;number:string;neighborhood:string;reference:string;payment:'pix'|'credito'|'dinheiro';change:string};
const empty:Checkout={name:'',phone:'',street:'',number:'',neighborhood:'',reference:'',payment:'pix',change:''};
const money=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

export default function Page(){
 const [products,setProducts]=useState<Product[]>([]),[cart,setCart]=useState<CartItem[]>([]),[cartOpen,setCartOpen]=useState(false),[checkoutOpen,setCheckoutOpen]=useState(false),[data,setData]=useState<Checkout>(empty),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{supabase.rpc('get_hey_roll_catalog').then(({data,error})=>{if(error)setError('Não foi possível carregar o cardápio.');else setProducts((data??[]) as Product[])})},[]);
 const total=useMemo(()=>cart.reduce((s,i)=>s+i.product_price*i.quantity,0),[cart]); const qty=useMemo(()=>cart.reduce((s,i)=>s+i.quantity,0),[cart]);
 const add=(p:Product)=>setCart(c=>{const x=c.find(i=>i.product_id===p.product_id);return x?c.map(i=>i.product_id===p.product_id?{...i,quantity:i.quantity+1}:i):[...c,{...p,quantity:1}]});
 const change=(id:string,d:number)=>setCart(c=>c.flatMap(i=>i.product_id!==id?[i]:i.quantity+d>0?[{...i,quantity:i.quantity+d}]:[]));
 async function finish(){if(!cart.length)return; if(!data.name||!data.phone||!data.street||!data.number||!data.neighborhood){setError('Preencha nome, telefone e endereço completo.');return} if(data.payment==='dinheiro'&&(!data.change||Number(data.change)<total)){setError('Informe um valor de troco maior ou igual ao total.');return} setBusy(true);setError('');
  const {data:r,error:e}=await supabase.rpc('create_hey_roll_order',{p_customer_name:data.name,p_customer_phone:data.phone,p_street:data.street,p_number:data.number,p_neighborhood:data.neighborhood,p_reference:data.reference,p_payment_type:data.payment,p_change_for:data.payment==='dinheiro'?Number(data.change):null,p_items:cart.map(i=>({product_id:i.product_id,quantity:i.quantity}))});
  if(e||!r?.[0]){setError(e?.message??'Erro ao registrar pedido.');setBusy(false);return} const n=r[0].order_number; const lines=cart.map(i=>`• ${i.quantity}x ${i.product_name} — ${money(i.product_price*i.quantity)}`).join('\n'); const pay=data.payment==='pix'?'PIX':data.payment==='credito'?'Cartão':'Dinheiro'; const msg=`*HEY ROLL LET'S GO — PEDIDO #${n}*\n\n*🍔 PEDIDO*\n${lines}\n\n*TOTAL: ${money(total)}*\n\n*📍 ENTREGA*\nNome: ${data.name}\nTelefone: ${data.phone}\nRua: ${data.street}, ${data.number}\nBairro: ${data.neighborhood}\nReferência: ${data.reference||'Não informado'}\n\n*💳 PAGAMENTO*\nForma: ${pay}${data.payment==='dinheiro'?`\nValor para troco: ${money(Number(data.change))}\nTroco: ${money(Number(data.change)-total)}`:''}\n\n*HEY HO, LET'S EAT! 🤘*`; window.open(`https://wa.me/${WA}?text=${encodeURIComponent(msg)}`,'_blank','noopener,noreferrer'); setCart([]);setData(empty);setCheckoutOpen(false);setCartOpen(false);setBusy(false);
 }
 const groups=products.reduce<Record<string,Product[]>>((a,p)=>{const k=p.category_name??'Outros';(a[k]??=[]).push(p);return a},{});
 return <main className="min-h-screen bg-[#050505] text-white">
  <header className="sticky top-0 z-40 border-b border-white/10 bg-black/95 backdrop-blur"><div className="mx-auto flex min-h-[88px] max-w-[1500px] items-center px-6 gap-6"><a href="#top" className="flex items-center gap-4"><img src={LOGO} className="h-[76px] w-[76px] rounded-full object-cover" alt="Hey Roll Let's Go"/><div className="hidden sm:block leading-none"><div className="rock-title text-[28px]">HEY ROLL</div><div className="rock-title mt-1 text-[26px] text-[#d71920]">LET’S GO</div></div></a><nav className="desktop-nav ml-auto hidden items-center gap-10 lg:flex">{[['INÍCIO','#top'],['CARDÁPIO','#menu'],['COMBOS','#combos'],['SOBRE NÓS','#sobre'],['CONTATO','#contato']].map(([l,h],i)=><a key={l} className={`nav ${i===0?'text-[#e11920]':''} flex items-center`} href={h}>{l}{i===0&&<Star size={18} fill="currentColor" className="ml-1 mt-7"/>}</a>)}</nav><button onClick={()=>setCartOpen(true)} className="ml-auto flex items-center gap-3 rounded bg-[#d71920] px-5 py-3 font-black uppercase hover:bg-white hover:text-black lg:ml-8"><ShoppingCart size={21}/> <span className="hidden sm:inline">Carrinho</span><b className="rounded-full bg-black px-2 py-1 text-xs">{qty}</b></button></div></header>
  <section id="top" className="texture border-b border-[#6f1116]"><div className="hero-grid mx-auto grid min-h-[650px] max-w-[1500px] items-center gap-8 px-6 py-12 lg:grid-cols-[1fr_1fr]"><div><div className="mb-8 flex items-center gap-4 text-lg font-black uppercase tracking-widest text-[#d71920]"><Star fill="currentColor"/> HAMBURGUERIA ARTESANAL <Star fill="currentColor"/></div><h1 className="rock-title hero-title text-[92px] leading-[.8] sm:text-[115px] lg:text-[145px]">HEY ROLL<br/><span className="text-[#e11920]">LET’S GO</span></h1><p className="hero-copy mt-8 text-2xl">Hambúrgueres artesanais na hamburgueria artesanal! 🍔</p><button onClick={()=>document.getElementById('menu')?.scrollIntoView({behavior:'smooth'})} className="mt-8 flex items-center gap-5 rounded bg-[#e11920] px-7 py-4 text-lg font-black uppercase hover:bg-white hover:text-black">ABRIR O CARDÁPIO <ArrowRight/></button></div><div className="hero-logo flex justify-center lg:justify-end"><img src={LOGO} alt="Logo oficial Hey Roll Let's Go Hamburgueria Artesanal" className="w-full max-w-[620px] rounded-full object-contain"/></div></div>
   <div className="info-grid mx-auto grid max-w-[1380px] gap-4 px-6 pb-8 md:grid-cols-3"><div className="info flex items-center gap-5 p-6"><Clock3 size={55} className="shrink-0 text-[#d71920]"/><div><h3 className="text-lg font-black">HORÁRIO DE FUNCIONAMENTO</h3><p className="mt-2 text-white/65">Terça a Domingo: 18:00 às 00:00</p><strong className="text-[#e11920]">Segunda: Fechado</strong></div></div><div className="info flex items-center gap-5 p-6"><Truck size={55} className="shrink-0 text-[#d71920]"/><div><h3 className="text-lg font-black">DELIVERY</h3><p className="mt-2 text-white/65">Rápido, quente e com muito Rock ’n’ Roll!</p></div></div><div className="info flex items-center gap-5 p-6"><MapPin size={55} className="shrink-0 text-[#d71920]"/><div><h3 className="text-lg font-black">ENDEREÇO</h3><p className="mt-2 text-white/65">R. Miguel Gonçalves, 218<br/>Bela Vista, Fortaleza - CE<br/>60420-480</p></div></div></div>
  </section><div className="starstrip py-2 text-center text-2xl">☆ ★ ☆ ★ ☆ ★ ☆ ★ ☆ ★ ☆ ★ ☆ ★ ☆ ★ ☆ ★ ☆ ★ ☆ ★ ☆ ★ ☆ ★</div>
  <section id="menu" className="mx-auto max-w-[1380px] px-6 py-16"><div className="mb-10 flex items-end justify-between border-b border-white/10 pb-5"><div><p className="font-black uppercase tracking-[.3em] text-[#d71920]">O PALCO ESTÁ ABERTO</p><h2 className="rock-title mt-2 text-6xl">CARDÁPIO</h2></div><span className="text-right text-xs font-black text-white/45">DIARIAMENTE<br/>A PARTIR DAS 18H</span></div>
   {products.length>0&&<div className="quick mb-10 p-5"><p className="font-black uppercase tracking-[.3em] text-[#d71920]">ATENDIMENTO RÁPIDO</p><h3 className="rock-title mt-1 text-3xl">UM CLIQUE. UM HIT.</h3><div className="mt-4 flex gap-2 overflow-x-auto pb-2">{products.slice(0,14).map(p=><button key={p.product_id} onClick={()=>add(p)} className="flex shrink-0 items-center gap-2 px-3 py-3 text-left text-xs font-black uppercase"><Plus size={15}/>{p.product_name}<span className="text-white/55">{money(p.product_price)}</span></button>)}</div></div>}
   {error&&<div className="mb-5 border border-[#d71920]/50 bg-[#d71920]/10 p-4 font-bold">{error}</div>}
   {Object.keys(groups).length===0?<div className="border border-dashed border-white/15 p-20 text-center"><h3 className="rock-title text-4xl">O PALCO ESTÁ SENDO MONTADO.</h3><p className="mt-3 text-white/45">Cadastre os produtos em Configurações.</p><a className="mt-6 inline-block bg-[#d71920] px-6 py-3 font-black uppercase" href="/configuracoes">Abrir configurações</a></div>:Object.entries(groups).map(([cat,items])=><div key={cat} className="mb-14"><div className="mb-6 flex items-center gap-4"><Star size={18} fill="#d71920" className="text-[#d71920]"/><h3 className="rock-title text-3xl">{cat}</h3></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{items.map(p=><article key={p.product_id} className="card overflow-hidden"><div className="relative aspect-[4/3] bg-black">{p.product_image_url?<img src={p.product_image_url} alt={p.product_name} className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center rock-title text-5xl text-white/10">HRLG</div>}{p.product_badge&&<span className="absolute left-3 top-3 bg-[#d71920] px-2 py-1 text-[10px] font-black uppercase">★ {p.product_badge}</span>}</div><div className="p-5"><h4 className="rock-title text-2xl">{p.product_name}</h4><p className="mt-2 min-h-12 text-sm leading-6 text-white/55">{p.product_description}</p><div className="mt-5 flex items-center justify-between"><b className="text-xl">{money(p.product_price)}</b><button onClick={()=>add(p)} className="flex items-center gap-2 bg-[#d71920] px-4 py-3 text-xs font-black uppercase hover:bg-white hover:text-black"><Plus size={17}/> Adicionar</button></div></div></article>)}</div></div>)}</section>
  <section id="combos" className="border-t border-white/10 bg-[#090909] px-6 py-20 text-center"><p className="font-black tracking-[.3em] text-[#d71920]">GRANDES HITS</p><h2 className="rock-title mt-3 text-5xl">COMBOS & ENCORES</h2><p className="mx-auto mt-4 max-w-xl text-white/55">Cadastre seus combos no painel e eles aparecerão aqui automaticamente.</p></section>
  <section id="sobre" className="px-6 py-20 text-center"><h2 className="rock-title text-5xl">SOBRE NÓS</h2><p className="mx-auto mt-5 max-w-2xl text-white/60">Hey Roll Let's Go Hamburgueria Artesanal. Rock, parrilla e hambúrguer artesanal para pedir sem enrolação.</p></section>
  <section id="contato" className="border-t border-white/10 px-6 py-20 text-center"><h2 className="rock-title text-5xl">CONTATO</h2><p className="mt-5 text-white/60">R. Miguel Gonçalves, 218 — Bela Vista, Fortaleza - CE</p><a href="https://wa.me/5585992443472" target="_blank" rel="noreferrer" className="mt-6 inline-block bg-[#d71920] px-7 py-4 font-black uppercase">Falar no WhatsApp</a></section>
  {cartOpen&&<div className="fixed inset-0 z-50 bg-black/75 p-4" onClick={()=>setCartOpen(false)}><aside className="modal ml-auto flex h-full w-full max-w-md flex-col p-6" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><h2 className="rock-title text-3xl">CARRINHO</h2><button onClick={()=>setCartOpen(false)}><X/></button></div><div className="mt-6 flex-1 space-y-3 overflow-auto">{cart.length===0?<p className="py-16 text-center text-white/40">Seu carrinho está vazio.</p>:cart.map(i=><div key={i.product_id} className="border border-white/10 p-4"><div className="font-black uppercase">{i.product_name}</div><div className="mt-3 flex items-center justify-between"><span>{money(i.product_price*i.quantity)}</span><div className="flex items-center gap-2"><button className="border p-1" onClick={()=>change(i.product_id,-1)}><Minus size={15}/></button><b>{i.quantity}</b><button className="border p-1" onClick={()=>change(i.product_id,1)}><Plus size={15}/></button></div></div></div>)}</div><div className="border-t border-white/10 pt-5"><div className="flex justify-between text-xl font-black"><span>TOTAL</span><span>{money(total)}</span></div><button disabled={!cart.length} onClick={()=>setCheckoutOpen(true)} className="mt-4 w-full bg-[#d71920] py-4 font-black uppercase disabled:opacity-40">Finalizar pedido — Hey Ho, Let's Eat!</button></div></aside></div>}
  {checkoutOpen&&<div className="fixed inset-0 z-[60] overflow-auto bg-black/80 p-4"><div className="modal mx-auto my-6 max-w-2xl p-6"><div className="flex justify-between"><h2 className="rock-title text-3xl">FINALIZAR PEDIDO</h2><button onClick={()=>setCheckoutOpen(false)}><X/></button></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{[['name','Nome'],['phone','Telefone'],['street','Rua'],['number','Número'],['neighborhood','Bairro'],['reference','Ponto de referência']].map(([k,l])=><label key={k}><span className="mb-1 block text-[10px] font-black uppercase text-white/45">{l}</span><input className="field" required value={data[k as keyof Checkout] as string} onChange={e=>setData({...data,[k]:e.target.value})}/></label>)}</div><label className="mt-4 block"><span className="mb-1 block text-[10px] font-black uppercase text-white/45">Forma de pagamento</span><select className="field" value={data.payment} onChange={e=>setData({...data,payment:e.target.value as Checkout['payment']})}><option value="pix">PIX</option><option value="credito">Cartão</option><option value="dinheiro">Dinheiro</option></select></label>{data.payment==='dinheiro'&&<label className="mt-4 block"><span className="mb-1 block text-[10px] font-black uppercase text-white/45">Troco para quanto?</span><input className="field" type="number" min={total} step="0.01" value={data.change} onChange={e=>setData({...data,change:e.target.value})}/></label>}<div className="mt-6 flex items-center justify-between border-t border-white/10 pt-5"><b className="text-xl">TOTAL {money(total)}</b><button disabled={busy} onClick={finish} className="bg-[#d71920] px-7 py-4 font-black uppercase disabled:opacity-50">{busy?'ENVIANDO...':'ENVIAR PEDIDO'}</button></div>{error&&<p className="mt-4 text-sm font-bold text-[#ff5b61]">{error}</p>}</div></div>}
 </main>
}
